set nocompatible  
set spelllang=en
" set spell
syntax enable
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set number

" vim plug"""
call plug#begin('~/.vim/plugged')

Plug 'buoto/gotests-vim'
Plug 'ekalinin/dockerfile.vim'
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
Plug 'jremmen/vim-ripgrep'
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/vim-easy-align'
Plug 'liuchengxu/space-vim-dark'
Plug 'luochen1990/rainbow'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-commentary'
Plug 'rust-lang/rust.vim'
Plug 'valloric/youcompleteme'
Plug 'wakatime/vim-wakatime'
Plug 'nsf/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }

call plug#end()

  """"" Go Bindings """""
"au Filetype go nmap <leader>l :GoLint<CR>
"au Filetype go nmap <leader>b :GoToggleBreakpoint<CR>
"au Filetype go map <leader>d :GoDebug<CR>
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_fmt_command = 'goimports'
let g:go_fmt_autosave = 1
let g:go_mod_fmt_autosave = 1
let g:go_imports_autosave = 1


let g:go_term_enabled = 1
let g:go_list_type = "quickfix"


 let g:syntastic_always_populate_loc_list = 1
 let g:syntastic_auto_loc_list = 1
 let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_w = 1
"let g:syntastic_check_autosave = 1
 "let g:syntastic_go_checkers = ['gofmt', 'govet', 'revive', 'errcheck', 'deadcode', 'gometalinter', 'misspell']
 let g:syntastic_style_error_symbol='>>'
 let g:syntastic_style_warning_symbol='>>'
let g:go_metalinter_autosave = 1
let g:go_metalinter_enabled = ['gofmt', 'govet', 'revive', 'errcheck', 'deadcode', 'gosimple', 'ifeffassign', 'staticcheck', 'structcheck', 'typecheck','unused', 'varcheck', 'bodyclose', 'dogsled', 'goconst', 'gocyclo', 'importas', 'rowserrcheck', 'sqlclosecheck', 'misspell']
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
highlight SyntasticError ctermbg=231
highlight SyntasticWarningLine ctermbg=130

"python-mode
let g:pymode_python = 'python3'

" NerdTree
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Start NERDTree and put the cursor back in the other window.
augroup nerdtree_open
    autocmd!
    autocmd VimEnter * NERDTree | wincmd p
augroup END


" Exit Vim if NERDTree is the only window remaining in the only tab.
augroup nerdtree_close
	autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
augroup END

" RUST
let g:rustfmt_autosave = 1

" Rainbow Paranetheses
 let g:rainbow_active = 1 "set to 0 if you want to enable it later via :RainbowToggle

" space vim dark
colorscheme space-vim-dark
hi Normal     ctermbg=NONE guibg=NONE
hi LineNr     ctermbg=NONE guibg=NONE
hi SignColumn ctermbg=NONE guibg=NONE

